AWSTemplateFormatVersion: 2010-09-09
Description: Monitor a reindex operation by observing a kinesis stream.
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: flex-reindex-monitor-lambda
  App:
    Description: Application name
    Type: String
    Default: flex-reindex-monitor-lambda
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: CODE
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: composer-dist
  HandlerMethod:
    Description: Which method to call when receiving the events
    Type: String
    Default: 4
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
      Description: Monitor a reindex operation by observing a kinesis stream.
      Handler: !Sub ${HandlerMethod}
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 60
