AWSTemplateFormatVersion: 2010-09-09
Description: Monitor a reindex operation by observing a kinesis stream.
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: flex-reindex-monitor-lambda
  App:
    Description: Application name
    Type: String
    Default: flex-reindex-monitor-lambda
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: CODE
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: composer-dist
  HandlerMethod:
    Description: Which method to call when receiving the events
    Type: String
    Default: 4
  WriteProvisions:
    Default: "50"
    Description: Number of provisioned writes for the event tracking table
    Type: String
  ReadProvisions:
    Default: "5"
    Description: Number of provisioned reads for the event tracking table
    Type: String
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        - PolicyName: kinesis
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - kinesis:GetRecords
                - kinesis:GetShardIterator
                - kinesis:DescribeStream
                - kinesis:ListStreams
              Resource:
                - !Sub arn:aws:kinesis:eu-west-1:743583969668:stream/flexible-content-stream-reindex-draft-${Stage}
                - !Sub arn:aws:kinesis:eu-west-1:743583969668:stream/flexible-content-stream-reindex-live-${Stage}
        - PolicyName: dynamo
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDB}*
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
          DynamoTable: !Ref DynamoDB
      Description: Monitor a reindex operation by observing a kinesis stream.
      Handler: !Sub ${HandlerMethod}
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 60
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: composerId
          AttributeType: S
      KeySchema:
        - AttributeName: composerId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: Expires
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadProvisions
        WriteCapacityUnits:
          Ref: WriteProvisions
